export interface HelpArticle {
  slug: string;
  title: string;
  summary: string;
  metaTitle: string;
  metaDescription: string;
  targetKeyword: string;
  relatedArticles: string[];
  faqs: Array<{ question: string; answer: string }>;
  sections: Array<{
    id: string;
    title: string;
    content: string;
  }>;
}

export const helpArticles: HelpArticle[] = [
  // Article 1: Getting Started
  {
    slug: "getting-started",
    title: "Getting Started with MentionLayer: Your First 30 Minutes",
    summary:
      "Set up your agency, add your first client, run an AI visibility audit, and understand your baseline score — all in under 30 minutes.",
    metaTitle:
      "Getting Started with MentionLayer | AI Visibility Platform Setup Guide",
    metaDescription:
      "Learn how to set up your MentionLayer account, add clients with brand briefs, import keywords, and run your first AI visibility audit in under 30 minutes.",
    targetKeyword: "AI visibility platform getting started",
    relatedArticles: [
      "citation-engine",
      "ai-visibility-audit",
      "ai-monitor",
    ],
    faqs: [
      {
        question: "How long does it take to set up my first client?",
        answer:
          "About 10 minutes. You need a brand name, website URL, and a 2-3 paragraph brand brief. Keywords can be added manually or generated by AI. The initial AI visibility audit runs automatically after setup and takes 3-5 minutes.",
      },
      {
        question: "What should I put in the brand brief?",
        answer:
          "Describe what the business does, who it serves, and what makes it different — in 250 words or less. This text gets injected into every AI prompt, so specificity matters. Include concrete details like years in business, number of customers, and unique selling points. Avoid generic marketing fluff.",
      },
      {
        question: "How many keywords should I start with?",
        answer:
          "Start with 10-20 high-intent keywords. Focus on buying-intent terms that your ideal customer would actually search for. MentionLayer's AI can suggest additional keywords based on your brand brief and industry.",
      },
      {
        question: "Can I import keywords from other tools?",
        answer:
          "Yes. You can paste a comma-separated list or import from a CSV file. MentionLayer also has an AI keyword suggestion feature that generates relevant keywords from your brand brief.",
      },
      {
        question: "What happens after I run my first audit?",
        answer:
          "The audit scans 5 pillars — Citations, AI Presence, Entities, Reviews, and Press — and produces a composite AI Visibility Score from 0-100. You also get a prioritized action plan telling you exactly what to do first. Most new clients score between 15-35, which means massive opportunity.",
      },
    ],
    sections: [
      {
        id: "create-your-account",
        title: "Create Your Account & Agency Profile",
        content: `When you first sign up for MentionLayer, you'll set up your agency profile. This is your top-level account that contains all your clients.

[Screenshot: Agency setup form with name, logo, and owner email fields]

Your agency profile includes:
- **Agency name** — your business name (e.g., "Xpand Digital")
- **Owner email** — the primary contact for billing and admin
- **Logo** — displayed in the dashboard header and client reports

If you're a single brand (not an agency), just use your brand name as the agency name. MentionLayer works the same way either way — one agency with one client.`,
      },
      {
        id: "add-your-first-client",
        title: "Add Your First Client",
        content: `Click **Clients** in the sidebar, then **Add Client**. Each client represents a brand you're managing AI visibility for.

[Screenshot: New client form with brand brief, tone guidelines, and target audience fields]

The four fields that matter most:

**Brand Brief** — This is the single most important field in MentionLayer. Every AI-generated response, every classification decision, every audit scan uses this text. Write 2-3 paragraphs describing what the business does, who it serves, and what makes it different. Be specific. "We're a marketing agency" is useless. "We're a B2B SaaS content marketing agency that's generated $47M in pipeline for 200+ tech companies since 2019" is what you want.

**Tone Guidelines** — How should responses sound? Casual and helpful? Technical and authoritative? Include specific rules like "never use the word 'utilize'" or "always mention the free trial."

**Target Audience** — Who are you trying to reach? The more specific, the better the AI can craft responses that resonate.

**Key Differentiators** — What makes this brand different from competitors? These points get woven naturally into generated responses.`,
      },
      {
        id: "add-keywords",
        title: "Add Keywords to Power Discovery",
        content: `Keywords are the fuel for MentionLayer's discovery engine. They determine which Reddit threads, Quora questions, and Facebook Group discussions get surfaced.

[Screenshot: Keyword management screen with tags, intent classification, and bulk import]

**Manual entry:** Type keywords one at a time. Good for starting out.

**AI suggestions:** Click "Suggest Keywords" and MentionLayer generates relevant keywords based on your brand brief and industry. Review and add the ones that match buying intent.

**Bulk import:** Paste a comma-separated list or upload a CSV. Useful if you already have keyword research from tools like Ahrefs or Semrush.

**Tips for great keywords:**
- Focus on **buying-intent** terms: "best [product category]", "[product] alternatives", "[product] vs [competitor]"
- Include **question-format** keywords: "how to choose a [product]", "is [product type] worth it"
- Add **competitor comparison** keywords: "[competitor] alternative", "[competitor] vs [your brand]"
- Don't go too broad. "Marketing" is useless. "B2B SaaS content marketing agency" finds the right threads.

Each keyword can be tagged with categories and assigned to specific platforms (Reddit, Quora, Facebook Groups). By default, all platforms are enabled.`,
      },
      {
        id: "run-your-first-audit",
        title: "Run Your First AI Visibility Audit",
        content: `Once you've added keywords, MentionLayer can run a baseline audit. This scans 5 pillars to measure your current AI visibility.

[Screenshot: Audit progress screen showing 5 pillars being scanned]

The audit takes 3-5 minutes and checks:

1. **Citations (25%)** — How many high-authority forum threads mention your brand vs competitors
2. **AI Presence (30%)** — Whether ChatGPT, Perplexity, Gemini, and Claude recommend you
3. **Entities (15%)** — Whether your brand identity is consistent across platforms AI models reference
4. **Reviews (15%)** — Your review presence and sentiment across key platforms
5. **Press (15%)** — Your earned media footprint and authority signals

Most new clients score between 15-35 out of 100. That's normal — it means there's massive opportunity. The audit also generates a prioritized action plan telling you exactly what to tackle first.

Read the full breakdown in [The AI Visibility Audit](/help/ai-visibility-audit).`,
      },
      {
        id: "explore-your-dashboard",
        title: "Explore Your Dashboard & Next Steps",
        content: `After the audit, your dashboard populates with data. Here's where to go next:

**Citation Engine** — Your daily working screen. This shows all discovered threads where you can place your brand. Start by generating responses for the highest-scoring threads.

**AI Monitor** — Set up monitoring prompts to track whether AI models start mentioning your brand over time. This is your north-star metric.

**Reports** — View your audit results, export PDF reports for clients, and track month-over-month progress.

[Screenshot: Dashboard overview with stats cards and module navigation]

**Recommended first actions:**
1. Review your audit action plan — it tells you exactly what to do first
2. Go to Citation Engine and generate responses for your top 5 threads
3. Set up 5-10 monitoring prompts in AI Monitor
4. Schedule your next audit for 30 days out

The discovery engine runs automatically twice per week, so new threads will keep appearing in your queue. Your job is to review, generate responses, and post them.`,
      },
    ],
  },

  // Article 2: Citation Engine
  {
    slug: "citation-engine",
    title:
      "How the Citation Engine Works: Finding & Seeding High-Authority Threads",
    summary:
      "The Citation Engine discovers Reddit, Quora, and Facebook Group threads that Google and AI models already reference, then generates human-quality responses to place your brand.",
    metaTitle:
      "Citation Engine Guide | Reddit & Quora AI Citation Seeding Tool",
    metaDescription:
      "Learn how MentionLayer's Citation Engine discovers high-authority forum threads on Reddit and Quora, generates 3 response variants, and helps you seed brand citations where AI models look.",
    targetKeyword: "citation seeding Reddit Quora AI visibility",
    relatedArticles: ["getting-started", "ai-monitor", "mention-gaps"],
    faqs: [
      {
        question: "How often does the discovery scan run?",
        answer:
          "Automatically twice per week (Tuesday and Friday). You can also trigger a manual scan anytime from the Citation Engine page. Each scan checks Google SERPs and AI models for new threads matching your keywords.",
      },
      {
        question: "What's the difference between the 3 response variants?",
        answer:
          "Casual Helper sounds like someone who stumbled across the thread and has personal experience. Expert Authority leads with deep domain knowledge and positions the brand as one option among several. Story-Based shares a personal experience where the brand mention feels incidental. Pick whichever fits the thread's tone best.",
      },
      {
        question: "How do I copy and post a response?",
        answer:
          "Click the copy icon on any response variant. It copies the full text to your clipboard. Then navigate to the actual thread on Reddit/Quora and paste it as a comment. Come back to MentionLayer and click 'Mark as Posted' to track it.",
      },
      {
        question: "Why are some threads marked as 'expired'?",
        answer:
          "Threads get marked expired when they're locked, archived, or too old to accept new comments. Reddit archives threads after 6 months by default. MentionLayer checks thread status during enrichment and automatically marks stale threads.",
      },
      {
        question: "How is the opportunity score calculated?",
        answer:
          "It's a composite of four signals: relevance to your brand (35%), Google SERP position (25%), thread recency (20%), and engagement level (20%). A thread ranking #3 on Google with 50+ comments and high relevance to your brand will score 80+.",
      },
    ],
    sections: [
      {
        id: "discovery-pipeline",
        title: "The Discovery Pipeline: How Threads Are Found",
        content: `MentionLayer's discovery engine runs a multi-step pipeline to find the highest-value threads for your brand.

[Screenshot: Discovery pipeline diagram showing SERP scan → AI probing → dedup → enrichment → classification]

**Step 1: SERP Scanning** — For each of your keywords, MentionLayer searches Google for Reddit, Quora, and Facebook Group results. It looks for queries like "site:reddit.com best music licensing" and captures the top 20 results per keyword. Threads ranking high on Google are the ones AI models are most likely to reference.

**Step 2: AI Probing** — MentionLayer asks Perplexity and ChatGPT buying-intent questions about your keywords and collects the source URLs they cite. These are threads that AI models already reference — the highest-value targets for citation seeding.

**Step 3: Deduplication** — Content hashing ensures the same thread never appears twice in your queue, even if discovered through multiple keywords or scans.

**Step 4: Thread Enrichment** — Full thread content gets pulled: the original post, top 15 comments (2 levels deep), upvote counts, comment counts, and post dates. This context is essential for generating relevant responses.

**Step 5: AI Classification** — Claude Sonnet analyzes each thread against your brand brief to determine intent (informational, transactional, commercial), relevance score, whether your brand can be naturally mentioned, and a suggested response angle.

**Step 6: Opportunity Scoring** — A composite score (0-100) ranks threads by their potential value. Threads scoring 70+ auto-advance to your queue. Threads scoring 40-69 stay for manual review. Below 40 get auto-skipped.`,
      },
      {
        id: "thread-queue",
        title: "The Thread Queue: Your Daily Working Screen",
        content: `The thread queue is where you spend most of your time in MentionLayer. It's a filterable, sortable table of all discovered threads for your selected client.

[Screenshot: Thread queue table with platform badges, intent tags, relevance bars, and action buttons]

**Key columns:**
- **Platform** — Reddit, Quora, or Facebook Groups (color-coded badges)
- **Community** — The specific subreddit, Quora topic, or Facebook Group
- **Title** — The thread title (click to open on the source platform)
- **Keyword** — Which of your keywords matched this thread
- **SERP Position** — Where this thread ranks on Google (lower = better)
- **Intent** — Informational, transactional, commercial, or navigational
- **Relevance** — How closely this thread matches your brand (0-100 bar)
- **Comments** — Thread engagement level
- **Date** — When the thread was posted
- **Status** — New, classified, queued, responded, posted, or skipped

**Filters:** Narrow your view by platform, intent type, relevance range, status, date range, or search by title text. The default view shows "queued" threads sorted by opportunity score (highest first).

**Pro tip:** Focus on threads with opportunity scores above 70 first. These are the ones where a well-placed response has the highest chance of being seen by both humans and AI crawlers.`,
      },
      {
        id: "response-generation",
        title: "Generating Responses: 3 Variants Built for Authenticity",
        content: `Click "Generate" on any thread to create three response variants using Claude Opus. Each variant is crafted to sound like a genuine community member — not a marketer.

[Screenshot: Response panel showing casual, expert, and story tabs with quality scores]

**Casual Helper** — Short, punchy, conversational. Mentions the brand as "I've been using X" or "a friend put me onto X." Feels like a quick helpful reply between meetings. Best for high-traffic Reddit threads where brevity wins.

**Expert Authority** — Leads with substantial advice that would be helpful even without the brand mention. Positions the brand as one option among several. Structured, thorough, credible. Typically the highest quality score. Best for Quora and in-depth Reddit threads.

**Story-Based** — Opens with "I was in the exact same boat as you..." and shares a personal experience where the brand mention feels incidental. Emotionally engaging. Best for threads where the OP is asking for personal recommendations.

**What makes these responses different from AI slop:**
- Never starts with "Great question!" or generic openers
- References specific details from the thread (OP's situation, other comments)
- Provides genuine value before any brand mention
- Matches platform culture (Reddit casual, Quora formal)
- Occasionally mentions competitors positively (credibility through balance)
- Uses imperfect formatting on Reddit (markdown, "edit: typo" style)

Each response includes a quality score (0-100), tone match score, and indicators for whether it mentions the brand name or URL.`,
      },
      {
        id: "posting-best-practices",
        title: "Best Practices for Posting Responses",
        content: `MentionLayer generates responses but never auto-posts them. You copy and paste manually. This is intentional — human review ensures quality and lets you adapt to the thread's current state.

**Before posting:**
1. **Read the thread** — Click the thread link to open it on the source platform. Check if new comments have been added since enrichment.
2. **Pick the right variant** — Match the variant to the thread's tone. Casual threads don't need expert-length answers. Emotional threads deserve stories.
3. **Edit if needed** — Click "Edit" to modify before copying. Adjust references, add personal touches, or tweak the brand mention placement.
4. **Check timing** — For threads older than 30 days, the response automatically includes a "late to this thread but..." opener. For very old threads, consider whether posting is still valuable.

**After posting:**
1. **Mark as Posted** — Click "Mark as Posted" in MentionLayer to track your placement rate.
2. **Monitor the thread** — Check back after 24-48 hours. Upvotes and replies indicate the response landed well.
3. **Track in AI Monitor** — Set up monitoring prompts to see if your seeded citations start showing up in AI model responses.

**Account management tips:**
- Use established Reddit/Quora accounts with karma and post history
- Don't post responses to multiple threads in the same subreddit within minutes
- Vary your language patterns — don't post all three variants across different threads
- Engage naturally: upvote other helpful comments, reply to follow-ups`,
      },
    ],
  },

  // Article 3: AI Monitor
  {
    slug: "ai-monitor",
    title:
      "AI Monitor: Track Your Brand's Visibility Across ChatGPT, Perplexity & Gemini",
    summary:
      "The AI Monitor tests whether ChatGPT, Perplexity, Gemini, and Claude mention your brand when asked buying-intent questions — and tracks your share of model over time.",
    metaTitle:
      "AI Monitor Guide | Track Brand Visibility in ChatGPT, Perplexity & Gemini",
    metaDescription:
      "Learn how MentionLayer's AI Monitor tracks your brand's share of model across ChatGPT, Perplexity, Gemini, and Claude. Set up prompts, monitor trends, and prove AI visibility ROI.",
    targetKeyword: "track brand visibility ChatGPT Perplexity AI monitor",
    relatedArticles: [
      "ai-visibility-audit",
      "citation-engine",
      "roi-reporting",
    ],
    faqs: [
      {
        question: "Which AI models does the monitor test?",
        answer:
          "ChatGPT (GPT-4o), Perplexity (Sonar Pro), Google Gemini, and Claude. Each model is tested independently with the same prompts, so you can see which models mention your brand and which don't.",
      },
      {
        question: "What is share-of-model?",
        answer:
          "Share of model measures what percentage of relevant AI prompts result in your brand being mentioned or recommended. If you test 40 prompts across 4 models and your brand appears in 8 responses, your share of model is 20%. Think of it like share of voice, but for AI recommendations.",
      },
      {
        question: "How often should I test?",
        answer:
          "Weekly is the default and recommended frequency. AI models update their training data periodically, so weekly testing catches changes quickly. For clients in fast-moving categories, you can set individual prompts to daily testing.",
      },
      {
        question: "Can I track competitor visibility too?",
        answer:
          "Yes. The AI Monitor automatically extracts competitor mentions from every test response. Over time, you can see how your share of model compares to competitors and whether your citation seeding is closing the gap.",
      },
    ],
    sections: [
      {
        id: "what-is-ai-monitoring",
        title: "What AI Monitoring Measures & Why It Matters",
        content: `AI Monitor answers the question every brand should be asking: "When someone asks ChatGPT about my industry, does it mention my brand?"

[Screenshot: AI Monitor overview showing share-of-model score, model breakdown, and trend chart]

Traditional SEO tracks Google rankings. MentionLayer's AI Monitor tracks **AI rankings** — whether your brand appears in the responses of ChatGPT, Perplexity, Gemini, and Claude when people ask buying-intent questions.

This matters because AI-powered search is growing fast. Perplexity alone processes millions of queries daily, and ChatGPT's browsing feature sends traffic directly from AI conversations. If your brand isn't being recommended by these models, you're invisible to a growing segment of potential customers.

**Key metrics the AI Monitor tracks:**
- **Share of Model** — The percentage of test prompts where your brand is mentioned
- **Mention Rate per Model** — Which AI models mention you vs which don't
- **Recommendation Rate** — Not just mentioned, but actively recommended
- **Link Citation Rate** — How often AI models link to your content
- **Competitor Share** — How your competitors compare on the same prompts
- **Trend Over Time** — Whether your visibility is improving or declining`,
      },
      {
        id: "setting-up-prompts",
        title: "Setting Up Monitoring Prompts",
        content: `Monitoring prompts are the questions you send to AI models to test brand visibility. MentionLayer generates suggested prompts from your keywords, but you can also write custom ones.

[Screenshot: Prompt management screen with prompt list, frequency selector, and model toggles]

**Auto-generated prompts** use your keywords to create buying-intent questions:
- "What are the best [keyword] options?"
- "Can anyone recommend a good [keyword] service?"
- "I need help with [keyword] — what do people suggest?"
- "Compare the top [keyword] companies"

**Custom prompts** let you test specific scenarios:
- "[Competitor] alternatives that are more affordable"
- "Best [product category] for [specific use case]"
- "Is [your brand] worth it compared to [competitor]?"

**Tips for effective prompts:**
- Write prompts the way real people ask AI models (conversational, specific)
- Include comparison prompts ("[Brand A] vs [Brand B]")
- Test different intent levels: informational, commercial, transactional
- Start with 10-15 prompts and add more as you identify gaps
- Each prompt can be configured to test specific models and run on a specific schedule (daily, weekly, biweekly, monthly)`,
      },
      {
        id: "reading-results",
        title: "Reading the Timeline & Trend Data",
        content: `The AI Monitor dashboard shows your visibility data in three views.

[Screenshot: Timeline view showing share-of-model trend line with event markers for citation placements]

**Overview** — Your current share of model, broken down by AI model. A stacked bar chart shows which models mention you vs which mention competitors.

**Timeline** — A trend line showing your share of model over weeks/months. Event markers highlight when you placed citations or ran press campaigns, so you can correlate actions to visibility changes.

**Results Detail** — Individual test results showing the exact prompt, the AI model's full response, whether your brand was mentioned, the context of the mention, and which sources were cited.

**What good looks like:**
- Share of model above 30% = strong visibility
- Share of model 10-30% = growing, keep seeding
- Share of model below 10% = early stage, focus on citation volume
- Upward trend = your seeding strategy is working
- Flat line = check that you're posting responses and that they're getting engagement`,
      },
      {
        id: "alerts-and-automation",
        title: "Setting Up Alerts",
        content: `Configure alerts to get notified when important changes happen to your AI visibility.

[Screenshot: Alert configuration showing threshold settings and notification channels]

**Available alert types:**
- **New brand mention** — Get notified when a new AI model starts mentioning your brand
- **Brand mention lost** — Alert when a model that was mentioning you stops
- **Competitor surge** — When a competitor's share of model jumps significantly
- **Share of model milestone** — Celebrate when you hit 10%, 25%, 50% share of model
- **Weekly digest** — Summary of all monitoring results sent every Monday

Alerts are sent via email to your registered address. In-app notifications appear in the bell icon in the dashboard header.

**Pro tip:** Set a "competitor surge" alert for your top 3 competitors. If a competitor suddenly jumps in AI visibility, investigate what they did — new press coverage, new forum posts, or updated content — and respond quickly.`,
      },
    ],
  },

  // Article 4: AI Visibility Audit
  {
    slug: "ai-visibility-audit",
    title: "The AI Visibility Audit: Understanding Your 5-Pillar Score",
    summary:
      "The AI Visibility Audit scans 5 pillars — Citations, AI Presence, Entities, Reviews, and Press — to produce a composite score and prioritized action plan.",
    metaTitle:
      "AI Visibility Audit Explained | 5-Pillar Score & Action Plan Guide",
    metaDescription:
      "Understand MentionLayer's AI Visibility Audit: how each of the 5 pillars is scored, what the composite score means, how to read the action plan, and when to re-audit.",
    targetKeyword: "AI visibility audit score pillars",
    relatedArticles: ["getting-started", "ai-monitor", "roi-reporting"],
    faqs: [
      {
        question: "How long does an audit take?",
        answer:
          "A full 5-pillar audit takes 3-5 minutes. You can watch each pillar complete in real-time on the progress screen. Quick audits (Citations + AI Presence only) take about 90 seconds.",
      },
      {
        question: "How often should I re-run the audit?",
        answer:
          "Monthly is ideal. Each audit is stored as a snapshot, so running monthly gives you a clear trend line. The month-over-month comparison is how you prove ROI to clients — 'Your AI Visibility Score went from 36 to 72 in 90 days.'",
      },
      {
        question: "What's a good AI Visibility Score?",
        answer:
          "Most new clients score 15-35. That's normal and means massive opportunity. A score of 50-65 means solid visibility with room to grow. Above 75 means you're a category leader in AI recommendations. The exact score matters less than the trend — are you going up month over month?",
      },
      {
        question: "Can I run an audit for a prospect before they sign up?",
        answer:
          "Yes, and you should. The audit works as a powerful sales tool. Run it for a prospect, show them where they score vs competitors, and present the action plan. The gaps sell the service for you.",
      },
      {
        question: "Why do my pillar scores add up to more than the composite?",
        answer:
          "The composite score is a weighted average, not a sum. Citations counts for 25%, AI Presence for 30%, Entities for 15%, Reviews for 15%, and Press for 15%. So a client with 80 in Reviews but 10 in AI Presence will still have a low composite because AI Presence carries more weight.",
      },
    ],
    sections: [
      {
        id: "what-the-audit-measures",
        title: "What the Audit Measures",
        content: `The AI Visibility Audit is your brand's comprehensive health check for the AI era. It answers: "If someone asks an AI about your industry, will it recommend you?"

[Screenshot: Audit results dashboard with circular composite score, 5 pillar bars, and executive summary]

The audit scans 5 pillars, each measuring a different dimension of AI visibility:

| Pillar | Weight | What It Measures |
|--------|--------|------------------|
| Citations | 25% | How many high-authority forum threads mention your brand vs competitors |
| AI Presence | 30% | Whether AI models actually recommend you when asked |
| Entities | 15% | Whether your brand identity is consistent across platforms AI models reference |
| Reviews | 15% | Your review presence and sentiment on key platforms |
| Press | 15% | Your earned media footprint and authority signals |

AI Presence carries the most weight because it's the most direct measure of what we're optimizing for. But all pillars feed into each other — strong citations lead to better AI presence, consistent entities help AI models trust your brand, and press coverage builds the authority signals AI models use to decide who to recommend.`,
      },
      {
        id: "pillar-deep-dive",
        title: "Deep Dive: How Each Pillar is Scored",
        content: `**Citations (25% of composite)**
Scans Google for Reddit, Quora, and Facebook Group threads matching your keywords. Checks whether your brand is mentioned in those threads, and whether competitors are. A client with 0 mentions in 142 threads where competitors appear 47 times has a massive citation gap.

Scoring factors: Brand mention rate (40%), competitor dominance ratio (30%), opportunity density (30%).

**AI Presence (30% of composite)**
Sends 10 buying-intent prompts to ChatGPT, Perplexity, Gemini, and Claude. Checks each response for brand mentions, recommendations, and link citations. This is the most direct measure of your AI visibility.

Scoring factors: Overall mention rate (50%), recommendation rate (30%), link citation rate (20%).

**Entities (15% of composite)**
Checks your brand's presence and consistency across Google Business, LinkedIn, Crunchbase, Wikipedia, industry directories, and social profiles. Also checks your website for schema markup (Organization, Product, FAQ). Inconsistencies confuse AI models.

Scoring factors: Platform coverage (25%), description consistency (35%), schema completeness (20%), knowledge panel presence (20%).

**Reviews (15% of composite)**
Scans Google Reviews, Trustpilot, G2, Capterra, and industry-specific platforms. Measures total volume, average rating, review recency, and velocity compared to competitors.

Scoring factors: Platform coverage (20%), rating score (25%), volume (25%), recency (15%), velocity vs competitors (15%).

**Press (15% of composite)**
Searches Google News and web results for brand mentions on third-party sites. Classifies mentions by type (news article, press release, guest post, podcast, award). Estimates domain authority of mentioning sites.

Scoring factors: Mention volume (20%), authority of publications (25%), diversity of mention types (20%), recency (15%), link ratio (10%), thought leadership (10%).`,
      },
      {
        id: "reading-the-action-plan",
        title: "Reading the Action Plan",
        content: `After all 5 pillars complete, Claude synthesizes the findings into a prioritized action plan ranked by impact-to-effort ratio.

[Screenshot: Action plan with numbered priorities, pillar tags, impact/effort ratings, and timeline estimates]

Each action item includes:
- **Priority number** — Do #1 first, then #2, and so on
- **Pillar** — Which pillar this action addresses (color-coded)
- **Specific action** — Not vague advice. Concrete steps like "Seed 20 high-authority Reddit threads where competitors are mentioned but you are not"
- **Impact** — High, medium, or low expected effect on your score
- **Effort** — High, medium, or low work required
- **Timeline** — How long this should take (e.g., "Week 1-2")
- **Module** — Which MentionLayer module handles this action

The action plan is designed as a campaign roadmap. Work through it top to bottom and re-audit monthly to track progress. Quick wins (high impact, low effort) are always listed first.

**Typical action plan for a new client:**
1. Seed high-authority citation threads (Citation Engine)
2. Fix entity inconsistencies (Entity Sync)
3. Launch targeted press campaign (PressForge)
4. Set up review request campaigns (Review Engine)
5. Optimize website schema for AI crawlers (Technical GEO)`,
      },
      {
        id: "monthly-re-auditing",
        title: "Monthly Re-Auditing for Progress Tracking",
        content: `Every audit is stored as a snapshot. Running monthly audits gives you a trend line that proves ROI.

[Screenshot: Month-over-month comparison showing score improvements across all 5 pillars]

**What to look for in monthly comparisons:**
- **Composite score trend** — Is the overall number going up? Even 5-10 points per month is solid progress.
- **Pillar-by-pillar movement** — Which pillars improved and which stalled? This tells you where to focus next month.
- **Citation gap closing** — Are you appearing in more threads than last month? Is the competitor dominance ratio shrinking?
- **AI Presence gains** — Are more AI models mentioning you? This is the lagging indicator — it takes 4-8 weeks of citation seeding before AI models start picking up your brand.
- **Action plan updates** — Each audit generates a fresh action plan based on current data, so priorities shift as you make progress.

**Reporting to clients:**
Export any audit as a PDF report. The report includes the composite score, pillar breakdown, executive summary, competitor comparison, action plan, and month-over-month trend data. This is the deliverable that justifies your fees — measurable, concrete, impossible to argue with.`,
      },
    ],
  },

  // Article 5: Entity Sync
  {
    slug: "entity-sync",
    title: "Entity Sync: Ensuring Your Brand Identity is Consistent for AI",
    summary:
      "Entity Sync scans your brand's presence across platforms AI models reference, identifies inconsistencies, and helps you build a canonical brand identity that AI can trust.",
    metaTitle:
      "Entity Sync Guide | Brand Identity Consistency for AI Visibility",
    metaDescription:
      "Learn how MentionLayer's Entity Sync ensures your brand identity is consistent across platforms that AI models reference. Fix inconsistencies, generate schema markup, and create llms.txt.",
    targetKeyword: "brand entity consistency AI visibility schema markup",
    relatedArticles: [
      "ai-visibility-audit",
      "technical-geo",
      "getting-started",
    ],
    faqs: [
      {
        question: "How does entity sync improve AI visibility?",
        answer:
          "AI models build their understanding of brands from multiple sources — LinkedIn, Google Business, Crunchbase, Wikipedia, your website schema. If these sources contradict each other (different descriptions, founding dates, categories), AI models lose confidence and are less likely to recommend you. Entity Sync ensures all sources tell the same story.",
      },
      {
        question: "What is llms.txt and do I need it?",
        answer:
          "llms.txt is a proposed standard (like robots.txt for AI) that tells AI crawlers key facts about your business in a structured format. MentionLayer generates this file for you based on your canonical brand description. While not universally adopted yet, early implementation signals AI-readiness and some models already reference it.",
      },
      {
        question:
          "What platforms does Entity Sync check?",
        answer:
          "Google Business Profile, LinkedIn, Crunchbase, Wikipedia/Wikidata, industry directories (varies by vertical), Twitter/X, Facebook, Instagram, your website's schema markup (Organization, Product, FAQ, BreadcrumbList), and Google Knowledge Panel presence.",
      },
      {
        question: "How often should I run an entity scan?",
        answer:
          "After initial cleanup, quarterly is sufficient. Entity data doesn't change as frequently as citations or AI mentions. Run a scan whenever you update your brand description, change business details, or launch on a new platform.",
      },
    ],
    sections: [
      {
        id: "why-entities-matter",
        title: "Why Entity Consistency Matters for AI",
        content: `AI models don't just crawl your website — they build an understanding of your brand from dozens of sources. If those sources tell different stories, the AI's confidence in your brand drops.

[Screenshot: Entity Sync dashboard showing platform presence, consistency score, and inconsistency alerts]

Think of it this way: if your LinkedIn says "music distribution company" but your Google Business says "music licensing service" and your Crunchbase says you were founded in 2019 while your website says 2018, an AI model has to decide which version is correct. Often, it just picks the most common answer — or worse, it picks a competitor whose information is consistent.

**Entity consistency directly impacts:**
- Whether AI models include you in recommendation lists
- The accuracy of how AI models describe your business
- Whether a Google Knowledge Panel appears for your brand
- How confidently AI models recommend you vs hedging with "according to some sources..."`,
      },
      {
        id: "platform-scanning",
        title: "Platform Profile Scanning",
        content: `Entity Sync searches Google for your brand name and identifies where your brand appears across key platforms.

[Screenshot: Platform scan results showing presence, description match scores, and missing platforms]

For each platform found, MentionLayer extracts your brand description and compares it to your canonical description (stored in MentionLayer). The match score (0-100) tells you how consistent each platform's description is.

**Platforms scanned:**
- Google Business Profile — Often the first thing AI models reference
- LinkedIn Company Page — Professional profile, frequently crawled
- Crunchbase — Business data that AI models trust for company facts
- Wikipedia / Wikidata — The gold standard for entity recognition
- Industry directories — G2, Capterra, Product Hunt, etc.
- Social profiles — Twitter/X, Facebook, Instagram

**What gets compared:**
- Business category/description
- Value proposition
- Contact information
- Founding date and location
- Key personnel
- Product/service offerings

Inconsistencies are flagged with specific details: "LinkedIn says 'music distribution' while Google says 'music licensing.'" This makes cleanup straightforward.`,
      },
      {
        id: "canonical-descriptions",
        title: "Setting Your Canonical Brand Description",
        content: `Your canonical description is the single source of truth for how your brand should be described everywhere. Entity Sync uses it as the benchmark for consistency checks.

[Screenshot: Canonical description editor with formatted text and character count]

**Writing a strong canonical description:**
- Start with what you do and who you serve (one sentence)
- Include your key differentiator (what makes you different)
- Add concrete proof points (years in business, customer count, notable clients)
- Keep it under 200 words — this needs to work on every platform
- Write in third person ("Xpand Digital is..." not "We are...")

Once set, MentionLayer generates platform-specific versions that preserve the core message while adapting length and format for each platform's requirements. You can review and edit each version before updating the actual platform profiles.`,
      },
      {
        id: "schema-and-llms-txt",
        title: "JSON-LD Schema & llms.txt Generation",
        content: `Entity Sync generates two technical assets that improve how AI models and search engines understand your brand.

**JSON-LD Schema Markup**
MentionLayer generates Organization, Product, FAQ, and BreadcrumbList schema markup based on your canonical description. Copy and paste the generated code into your website's head section (or use a schema plugin if you're on WordPress).

[Screenshot: Generated JSON-LD code snippet for Organization schema]

Schema markup helps both Google and AI models understand:
- What your business is (Organization type)
- What you sell (Product/Service types)
- Common questions about your business (FAQ type)
- Your site structure (BreadcrumbList type)

**llms.txt**
MentionLayer generates an llms.txt file — a structured document specifically designed for AI crawlers. It includes your brand name, description, key products/services, FAQs, and authoritative sources.

Place this file at yoursite.com/llms.txt (like robots.txt). While the standard is still emerging, Perplexity and some other AI models already look for it. Early adoption signals that your brand is AI-ready and helps models find accurate information about your business.`,
      },
    ],
  },

  // Article 6: Review Engine
  {
    slug: "review-engine",
    title: "Review Engine: Managing Reviews Across All Platforms",
    summary:
      "The Review Engine monitors reviews across Google, Trustpilot, G2, and more. Generate AI-powered review responses, run review request campaigns, and benchmark against competitors.",
    metaTitle:
      "Review Engine Guide | AI Review Management & Monitoring Platform",
    metaDescription:
      "Learn how MentionLayer's Review Engine monitors reviews across Google, Trustpilot, and G2, generates AI review responses, runs review request campaigns, and benchmarks competitors.",
    targetKeyword: "review management platform AI response generation",
    relatedArticles: [
      "ai-visibility-audit",
      "entity-sync",
      "roi-reporting",
    ],
    faqs: [
      {
        question: "What platforms does the review engine scan?",
        answer:
          "Google Reviews, Trustpilot, G2, Capterra, Yelp, Product Hunt, and industry-specific platforms. The specific platforms scanned depend on your business category. B2B software companies get G2 and Capterra. Local businesses get Yelp and Google Maps. E-commerce gets Trustpilot and Amazon.",
      },
      {
        question: "How do I set up review request campaigns?",
        answer:
          "Go to Review Engine → Campaigns → New Campaign. Set your target platform, review request email template (MentionLayer provides AI-generated templates), and delivery schedule. You can import a customer list or connect to your CRM. Reviews are requested via email with a direct link to the review platform.",
      },
      {
        question:
          "Can MentionLayer write review responses for me?",
        answer:
          "Yes. For each incoming review, MentionLayer generates a suggested response using Claude. Positive reviews get a grateful, personalized response. Negative reviews get an empathetic, solution-oriented response. You review and post manually — MentionLayer never auto-posts review responses.",
      },
      {
        question: "How do reviews affect AI visibility?",
        answer:
          "AI models use review signals as trust indicators. A brand with 500 reviews averaging 4.5 stars across 5 platforms is more likely to be recommended than one with 10 reviews on a single platform. Review volume, recency, platform diversity, and sentiment all influence AI recommendation likelihood.",
      },
    ],
    sections: [
      {
        id: "review-monitoring",
        title: "Review Scanning & Monitoring",
        content: `The Review Engine continuously monitors your brand's reviews across all relevant platforms.

[Screenshot: Review feed showing recent reviews across platforms with sentiment indicators]

**The review feed shows:**
- All reviews sorted by recency
- Platform source (Google, Trustpilot, G2, etc.)
- Star rating and sentiment analysis (positive, neutral, negative)
- Whether a response has been posted
- Review velocity trends (reviews per month over time)

New reviews trigger alerts based on your configuration. Negative reviews get flagged for immediate attention. The feed is filterable by platform, rating, sentiment, and response status.

**Aggregate metrics tracked:**
- Total reviews across all platforms
- Average rating (overall and per-platform)
- Review velocity (reviews per month, trending up or down)
- Sentiment distribution (positive/neutral/negative breakdown)
- Response rate (what percentage of reviews have a response)`,
      },
      {
        id: "review-response-generation",
        title: "AI-Powered Review Response Generation",
        content: `For each review, MentionLayer generates a suggested response using Claude. The response is tailored to the review's content, sentiment, and platform.

[Screenshot: Review response generator showing original review and generated response side by side]

**For positive reviews (4-5 stars):**
- Grateful, personalized response referencing specific points the reviewer mentioned
- Reinforces the positive experience
- Subtle encouragement to recommend to others
- Keeps it genuine — no marketing-speak

**For negative reviews (1-3 stars):**
- Empathetic opening acknowledging the frustration
- Specific response to the complaints raised
- Clear action steps being taken
- Invitation to continue the conversation privately
- Never defensive, never dismissive

**For neutral reviews (3 stars):**
- Appreciation for honest feedback
- Addresses any specific concerns
- Highlights features or changes that address their points

You review every suggested response before posting. Edit, approve, or reject as needed. MentionLayer never auto-posts review responses.`,
      },
      {
        id: "review-request-campaigns",
        title: "Review Request Campaigns",
        content: `Proactively growing your review count is critical for AI visibility. The Review Engine helps you run structured review request campaigns.

[Screenshot: Campaign setup showing email template, target platform, audience selection, and schedule]

**Campaign setup:**
1. **Choose a target platform** — Focus on one platform per campaign (e.g., Google Reviews this month, G2 next month)
2. **Select your audience** — Import a customer list, connect to your CRM, or manually add contacts
3. **Customize the template** — MentionLayer generates an email template. Edit the subject line, personalization fields, and messaging
4. **Set the schedule** — Drip-send review requests over time (not all at once) for natural-looking velocity
5. **Launch and track** — Monitor open rates, click rates, and actual reviews received

**Tips for high conversion rates:**
- Time requests 2-7 days after a positive interaction or purchase
- Keep the email short — one clear ask with a direct link to the review platform
- Use the customer's name and reference a specific interaction
- Send follow-up reminders (once) to non-responders after 5 days
- Never incentivize reviews — it violates most platform policies`,
      },
      {
        id: "competitor-benchmarking",
        title: "Competitor Review Benchmarking",
        content: `Track how your review presence compares to competitors across all platforms.

[Screenshot: Competitor comparison table showing review counts, ratings, and velocity per platform]

**Competitor tracking shows:**
- Total review count per competitor per platform
- Average rating per competitor
- Review velocity (are they growing faster than you?)
- Sentiment distribution comparison
- Platform coverage gaps (platforms where they have reviews and you don't)

This data feeds directly into your audit score and action plan. If a competitor has 4,200 reviews on Google while you have 23, the action plan will prioritize a Google review campaign.

**Key benchmarks to watch:**
- Your total reviews vs the category leader
- Your average rating vs category average
- Review platforms you're missing that competitors are on
- Review velocity trends — are you closing the gap or falling behind?`,
      },
    ],
  },

  // Article 7: PressForge
  {
    slug: "pressforge",
    title: "PressForge: AI-Powered Digital PR for AI Visibility",
    summary:
      "PressForge generates press ideas, writes releases, scores journalists, runs outreach sequences, and tracks coverage — all designed to build the authority signals AI models use to rank brands.",
    metaTitle:
      "PressForge Guide | AI-Powered Digital PR for Brand Authority",
    metaDescription:
      "Learn how MentionLayer's PressForge module generates press ideas, writes releases with AI, matches you with journalists, runs outreach campaigns, and tracks media coverage.",
    targetKeyword: "AI powered digital PR press release tool",
    relatedArticles: [
      "ai-visibility-audit",
      "citation-engine",
      "roi-reporting",
    ],
    faqs: [
      {
        question: "How do I generate a press release?",
        answer:
          "Go to PressForge → Campaigns → New Campaign. Select a press idea (AI-generated or custom), and MentionLayer drafts a full press release using Claude Opus. The draft follows AP style, includes quotes, statistics, and contact info. You review, edit, and approve before distribution.",
      },
      {
        question: "How does press coverage improve AI visibility?",
        answer:
          "AI models use third-party media mentions as authority signals. A brand mentioned in 15 high-authority publications is more trustworthy to an AI than one with zero press. Press coverage also generates backlinks that improve your Google rankings, which in turn improves the authority of forum threads where your brand is cited.",
      },
      {
        question: "How does the journalist matching work?",
        answer:
          "MentionLayer maintains a database of journalists scored by relevance to your industry, publication authority, recent coverage topics, and engagement rates. When you create a press campaign, the system suggests journalists ranked by fit score. You can also search and filter manually.",
      },
      {
        question: "Can I track which journalists actually cover my story?",
        answer:
          "Yes. PressForge's coverage tracker monitors Google News and web results for mentions of your brand + campaign topic after outreach. It identifies which publications covered the story, links back to your brand, and estimates the reach of each placement.",
      },
    ],
    sections: [
      {
        id: "press-idea-generation",
        title: "Press Idea Generation",
        content: `PressForge uses AI to generate newsworthy story angles based on your brand, industry trends, and competitive landscape.

[Screenshot: Press idea generator showing AI-suggested story angles with newsworthiness scores]

**How ideas are generated:**
- Analyzes your brand brief, industry, and key differentiators
- Scans current news trends in your category
- Identifies data-driven story angles (surveys, reports, benchmarks)
- Suggests thought leadership pieces based on your team's expertise
- Flags timely hooks (seasonal trends, industry events, regulatory changes)

**Idea types:**
- **Data stories** — "X% of [audience] are now using AI to [action]" (backed by your proprietary data or surveys)
- **Trend commentary** — Expert take on an industry trend, positioning your brand as a thought leader
- **Product launches** — New features, milestones, or partnerships worth announcing
- **Customer success** — Case studies with measurable results (with client permission)
- **Contrarian takes** — Industry hot takes that challenge conventional wisdom (great for engagement)

Each idea includes a newsworthiness score, suggested headline, target publications, and estimated timeline.`,
      },
      {
        id: "release-writing",
        title: "AI-Powered Release Writing & Editing",
        content: `Once you select a press idea, MentionLayer drafts a complete press release using Claude Opus.

[Screenshot: Press release editor showing AI-generated draft with editing tools]

**The draft includes:**
- AP-style headline and subheadline
- Dateline and lead paragraph (who, what, when, where, why)
- Body paragraphs with supporting details and context
- Quotes from company spokesperson (using your brand brief and tone)
- Boilerplate company description
- Contact information

**Editing workflow:**
1. Review the AI draft — check facts, quotes, and tone
2. Edit in the built-in editor (rich text with markdown support)
3. Add real quotes from team members (replace AI placeholders)
4. Run through the quality checker (readability, AP style compliance)
5. Approve for distribution

The release is stored in your campaign and can be exported as a formatted PDF, plain text, or HTML for your newsroom page.`,
      },
      {
        id: "journalist-matching",
        title: "Journalist Database & Scoring",
        content: `PressForge includes a journalist database to help you target the right people for each story.

[Screenshot: Journalist database with relevance scores, recent coverage topics, and contact info]

**Journalist scoring factors:**
- **Industry relevance** — Do they cover your category? (weighted highest)
- **Publication authority** — Domain authority and reach of their publication
- **Recent coverage** — Have they written about similar topics recently?
- **Engagement rate** — Do their articles get social shares and comments?
- **Responsiveness** — Historical response rate to pitches (improves over time with usage)

**Finding the right journalists:**
- Search by industry, publication, or topic
- Filter by authority level, location, and publication type
- Sort by fit score for your specific campaign
- Save favorites and build custom media lists

MentionLayer suggests the top 10-15 journalists for each campaign based on the story angle and your industry.`,
      },
      {
        id: "outreach-and-coverage",
        title: "Outreach Sequencing & Coverage Tracking",
        content: `Once your release is approved and journalists are selected, PressForge manages the outreach process.

[Screenshot: Outreach sequence showing email stages, response tracking, and follow-up schedule]

**Outreach sequence:**
1. **Initial pitch** — Personalized email introducing the story angle (not the full release)
2. **Follow-up** — If no response after 3 days, a shorter follow-up referencing the original pitch
3. **Release delivery** — When a journalist expresses interest, send the full release + assets

**Coverage tracking:**
After outreach, PressForge monitors Google News and web search for coverage. It tracks:
- Which publications ran the story
- Whether they linked back to your brand
- Estimated reach and domain authority of each placement
- Social shares and engagement on coverage articles
- Unlinked mentions (brand mentioned but no link — outreach opportunity)

Coverage results feed back into your audit's Press pillar score. More high-authority coverage = higher press score = higher composite AI Visibility Score.`,
      },
    ],
  },

  // Article 8: Technical GEO
  {
    slug: "technical-geo",
    title: "Technical GEO: Is Your Website Ready for AI Crawlers?",
    summary:
      "Technical GEO audits your robots.txt for AI bot access, measures content freshness and citation risk, calculates a citability score, and verifies schema markup and SSR.",
    metaTitle:
      "Technical GEO Guide | Robots.txt AI Crawler Audit & Citability Score",
    metaDescription:
      "Learn how MentionLayer's Technical GEO module audits your robots.txt for AI crawlers like GPTBot and ClaudeBot, measures content citability, and verifies schema markup for AI visibility.",
    targetKeyword:
      "robots.txt AI crawlers GPTBot ClaudeBot citability score",
    relatedArticles: ["entity-sync", "ai-visibility-audit", "mention-gaps"],
    faqs: [
      {
        question: "What does the Technical GEO scan check?",
        answer:
          "Three things: (1) Your robots.txt file — which AI crawlers are allowed and which are blocked, (2) Content freshness — how recently your key pages were updated and whether stale content is hurting citability, (3) Citability score — a composite measure of how easy it is for AI models to extract and cite information from your website.",
      },
      {
        question: "Why should I unblock AI crawlers in robots.txt?",
        answer:
          "If GPTBot, ClaudeBot, or PerplexityBot are blocked in your robots.txt, those AI models literally cannot read your website content. They'll rely entirely on third-party sources (forums, press, reviews) to learn about your brand — which may be incomplete or inaccurate. Unblocking AI crawlers lets them access your authoritative content directly.",
      },
      {
        question: "What AI crawlers exist?",
        answer:
          "The main ones are GPTBot (OpenAI/ChatGPT), ClaudeBot (Anthropic/Claude), PerplexityBot (Perplexity), Google-Extended (Gemini), Bytespider (TikTok), CCBot (Common Crawl), and Amazonbot. MentionLayer checks for all of these in your robots.txt.",
      },
      {
        question: "What is a citability score?",
        answer:
          "Citability measures how easy it is for AI models to extract useful, citable facts from your website. High citability means your content has clear headings, specific data points, FAQ sections, and structured markup. Low citability means AI models struggle to pull concrete information from your pages.",
      },
    ],
    sections: [
      {
        id: "robots-txt-auditing",
        title: "Robots.txt Auditing for AI Bots",
        content: `The first thing Technical GEO checks is your robots.txt file. This file controls which bots can crawl your website — and many sites are unknowingly blocking AI crawlers.

[Screenshot: Robots.txt audit showing allowed/blocked status for each AI crawler]

**AI crawlers MentionLayer checks for:**

| Bot | Company | Used By |
|-----|---------|---------|
| GPTBot | OpenAI | ChatGPT, Microsoft Copilot |
| ClaudeBot | Anthropic | Claude |
| PerplexityBot | Perplexity | Perplexity.ai |
| Google-Extended | Google | Gemini |
| Bytespider | ByteDance | TikTok AI |
| CCBot | Common Crawl | Training data for many models |
| Amazonbot | Amazon | Alexa AI |

**Common issues found:**
- **Blanket disallow** — "Disallow: /" for all bots blocks AI crawlers too
- **Overly restrictive rules** — Blocking entire directories that contain valuable content
- **Stale rules** — Old robots.txt that doesn't account for new AI crawlers
- **No explicit allow** — Some AI bots require explicit "Allow" rules to crawl

MentionLayer shows you exactly which bots are allowed and which are blocked, with specific line numbers in your robots.txt. It generates a recommended robots.txt that allows AI crawlers while maintaining any legitimate blocks you have.`,
      },
      {
        id: "content-freshness",
        title: "Content Freshness & Citation Risk",
        content: `AI models prefer fresh, authoritative content. Technical GEO analyzes your key pages for freshness signals.

[Screenshot: Content freshness report showing pages ranked by last-modified date and citation risk]

**What gets checked:**
- **Last-modified dates** on key pages (homepage, product pages, about page)
- **Publish dates** on blog posts and articles
- **Content staleness indicators** — References to past years, outdated statistics, deprecated features
- **Update velocity** — How often you publish or update content

**Citation risk assessment:**
Pages with outdated content are a citation risk. If an AI model cites your page that says "in 2023, the market is expected to grow..." — that makes your brand look stale. Technical GEO flags pages with the highest citation risk so you can prioritize updates.

**Content freshness score factors:**
- Average page age across key pages
- Percentage of pages updated in the last 90 days
- Blog publishing frequency
- Presence of "last updated" dates visible on pages`,
      },
      {
        id: "citability-scoring",
        title: "Citability Scoring Explained",
        content: `Citability measures how easy it is for AI models to extract specific, citable information from your website.

[Screenshot: Citability score breakdown showing per-page scores and improvement suggestions]

**High-citability content has:**
- Clear H2/H3 heading structure (AI models use headings to navigate)
- Specific data points and statistics (numbers are more citable than generalities)
- FAQ sections with concise answers (AI models love Q&A format)
- Lists and comparison tables (structured data is easier to parse)
- Author attribution and publication dates (trust signals)
- Proper schema markup (helps AI understand content structure)

**Low-citability content has:**
- Wall-of-text paragraphs with no headings
- Vague marketing copy with no specifics
- Content behind JavaScript rendering that AI crawlers can't access
- Missing meta descriptions and structured data
- No FAQ or knowledge-base style content

**The citability score (0-100) is based on:**
- Heading structure quality (20%)
- Specific, quotable statements per page (25%)
- FAQ/structured content presence (20%)
- Schema markup completeness (15%)
- SSR/crawlability (10%)
- Content depth and originality (10%)

MentionLayer provides page-by-page citability scores with specific recommendations for improvement.`,
      },
      {
        id: "schema-and-ssr",
        title: "Schema & SSR Verification",
        content: `Technical GEO verifies that your website's technical foundation supports AI crawling and understanding.

[Screenshot: Schema verification showing detected vs missing schema types and SSR status]

**Schema markup check:**
MentionLayer scans your website for JSON-LD structured data and reports which types are present vs missing. Key schema types for AI visibility:
- **Organization** — Your company identity
- **Product / Service** — What you sell
- **FAQ** — Common questions (highly cited by AI models)
- **Article** — Blog posts and content pieces
- **BreadcrumbList** — Site navigation structure
- **Review** — Customer reviews on your site
- **HowTo** — Step-by-step guides

**Server-Side Rendering (SSR) check:**
AI crawlers often can't execute JavaScript. If your content is client-side rendered (React SPA without SSR), AI bots may see a blank page. Technical GEO tests your key pages from a bot's perspective and flags any pages that require JavaScript to render content.

**Recommendations generated:**
- Missing schema types with ready-to-use JSON-LD code
- SSR configuration suggestions for your framework
- Meta tag improvements for better AI understanding
- Canonical URL and sitemap optimization tips`,
      },
    ],
  },

  // Article 9: Mention Gaps
  {
    slug: "mention-gaps",
    title: "Mention Gap Analysis: Finding Where Competitors Beat You",
    summary:
      "The Mention Gap Analyzer scans Reddit, Quora, YouTube, LinkedIn, G2, and more to find every place competitors are mentioned and you're not — then tells you how to close the gaps.",
    metaTitle:
      "Mention Gap Analysis Guide | Find Where Competitors Beat You in AI",
    metaDescription:
      "Learn how MentionLayer's Mention Gap Analyzer scans Reddit, Quora, YouTube, and more to find competitor mentions you're missing, and generates action plans to close the gaps.",
    targetKeyword: "mention gap analysis competitor AI visibility",
    relatedArticles: [
      "citation-engine",
      "ai-monitor",
      "ai-visibility-audit",
    ],
    faqs: [
      {
        question: "What is a mention gap?",
        answer:
          "A mention gap is any place where a competitor is mentioned or recommended and your brand is not. This could be a Reddit thread, a Quora answer, a YouTube video description, a G2 comparison page, or an AI model response. Each gap is a missed opportunity for visibility.",
      },
      {
        question:
          "How is mention gap analysis different from the Citation Engine?",
        answer:
          "The Citation Engine focuses on Reddit, Quora, and Facebook Groups — forums where you can directly post responses. The Mention Gap Analyzer casts a wider net across YouTube, LinkedIn, G2, Capterra, industry blogs, and more. It identifies gaps across all platforms, then routes actionable gaps to the right MentionLayer module.",
      },
      {
        question: "What can I do about YouTube mention gaps?",
        answer:
          "MentionLayer generates YouTube GEO video briefs — content outlines optimized for topics where competitors have video coverage and you don't. These briefs include suggested titles, key points to cover, keywords to mention, and competitor videos to reference. You or a video team produce the video using the brief.",
      },
      {
        question: "How often should I run a mention gap analysis?",
        answer:
          "Monthly is ideal, aligned with your audit schedule. The gap landscape changes as competitors publish new content and as your seeding efforts close existing gaps. Monthly analysis keeps your strategy focused on the most impactful opportunities.",
      },
    ],
    sections: [
      {
        id: "cross-platform-scanning",
        title: "Cross-Platform Mention Scanning",
        content: `The Mention Gap Analyzer goes beyond forum threads to scan every platform where your brand and competitors might be mentioned.

[Screenshot: Gap analysis overview showing platform-by-platform mention counts for brand vs competitors]

**Platforms scanned:**
- **Forums** — Reddit, Quora, Facebook Groups
- **Video** — YouTube video titles, descriptions, and comment sections
- **Professional** — LinkedIn posts and articles
- **Review sites** — G2, Capterra, Trustpilot, Product Hunt
- **Industry blogs** — Relevant publications in your category
- **AI models** — ChatGPT, Perplexity, Gemini, Claude responses

For each platform, MentionLayer counts mentions of your brand vs each competitor across the same keywords. The result is a clear map of where your competitors have presence and you don't.

**Gap severity levels:**
- **Critical** — Competitor mentioned 20+ times, you're at zero
- **High** — Competitor mentioned 10-19 times, you're under 3
- **Medium** — Competitor has 2x+ your mention count
- **Low** — Small gap or platform with lower impact`,
      },
      {
        id: "reading-the-gap-report",
        title: "Reading the Gap Report",
        content: `The gap report presents your mention data in multiple views to help you prioritize action.

[Screenshot: Gap report showing heatmap of competitor vs brand mentions by platform and keyword]

**Summary view** — High-level metrics: total gaps found, platforms with largest gaps, most-mentioned competitors, estimated traffic value of gaps.

**Platform breakdown** — For each platform, see the specific mentions your competitors have that you're missing. Sorted by impact (estimated reach × relevance).

**Keyword breakdown** — For each keyword, see which competitors appear and on which platforms. This reveals keyword-level blind spots.

**Competitor breakdown** — For each competitor, see their full mention footprint vs yours. Useful for competitive intelligence beyond just gaps.

**The gap heatmap** is particularly useful — it's a matrix of keywords × platforms, color-coded by gap severity. Dark red cells = massive opportunity. Green cells = you're winning.`,
      },
      {
        id: "acting-on-gaps",
        title: "Acting on Gaps: Routing to the Right Module",
        content: `Every identified gap links to the MentionLayer module that can close it.

[Screenshot: Gap action panel showing recommended actions with module links]

**Forum gaps → Citation Engine**
Competitor mentioned in Reddit/Quora threads where you're absent? The Citation Engine already has these threads in your queue. Generate responses and start seeding.

**Review gaps → Review Engine**
Competitor has 500 G2 reviews and you have 3? Launch a review request campaign targeting that specific platform.

**Press gaps → PressForge**
Competitor getting industry press coverage that you're not? Create a press campaign targeting the same publications with your story angle.

**Entity gaps → Entity Sync**
Competitor has a complete Crunchbase profile, Google Knowledge Panel, and Wikipedia page? Entity Sync helps you build those foundational profiles.

**Video gaps → YouTube GEO**
Competitor has YouTube content ranking for your keywords? YouTube GEO generates video briefs to close the gap.

**AI model gaps → Citation Engine + PressForge**
Competitor recommended by AI models where you're not? This is the compound effect — seeding citations and building press authority eventually shifts AI model recommendations in your favor.`,
      },
      {
        id: "youtube-geo-briefs",
        title: "YouTube GEO Video Briefs",
        content: `For mention gaps on YouTube, MentionLayer generates structured video briefs optimized for AI visibility.

[Screenshot: YouTube GEO brief showing title, outline, keywords, and competitor video analysis]

**Why YouTube matters for AI visibility:**
YouTube is the world's second-largest search engine, and AI models frequently cite YouTube content. A well-optimized video that ranks for your keywords becomes a citation source that AI models reference — extending your visibility beyond text-based platforms.

**What a video brief includes:**
- **Suggested title** — Optimized for both YouTube search and AI citation
- **Content outline** — 5-8 key sections with talking points
- **Keywords to mention** — Terms to include in the script, description, and tags
- **Competitor analysis** — What existing competitor videos cover and how to differentiate
- **Citation hooks** — Specific facts, data points, or frameworks to include that make the video more citable by AI models
- **SEO metadata** — Suggested description, tags, and thumbnail concepts

You (or your video production team) use the brief to create the actual video. The brief is designed so that even someone unfamiliar with the topic can produce a solid, authoritative video.`,
      },
    ],
  },

  // Article 10: ROI Reporting
  {
    slug: "roi-reporting",
    title: "Proving ROI: Before/After Audit Scores & Competitor Reports",
    summary:
      "Track your AI visibility progress with monthly audit comparisons, competitor intelligence reports, and GA4 attribution data that proves the value of AI citation campaigns.",
    metaTitle:
      "AI Visibility ROI Reporting | Audit Comparisons & Competitor Reports",
    metaDescription:
      "Learn how to prove ROI with MentionLayer's reporting: monthly audit score comparisons, competitor intelligence reports, GA4 attribution tracking, and client-ready PDF exports.",
    targetKeyword: "AI visibility ROI reporting audit comparison",
    relatedArticles: [
      "ai-visibility-audit",
      "ai-monitor",
      "getting-started",
    ],
    faqs: [
      {
        question: "How do I export a client report?",
        answer:
          "Go to Reports → select a date range → click 'Export PDF.' The report includes your current audit scores, month-over-month trends, citation placements, AI monitor results, and competitor comparison. It's formatted as a professional client deliverable with your agency branding.",
      },
      {
        question: "What does GA4 attribution tracking show?",
        answer:
          "GA4 attribution connects your Google Analytics data to show traffic and conversions that came from citation placements. When someone clicks a link in a Reddit thread where you seeded a response, GA4 tracks that visit and any resulting conversions (form fills, purchases, sign-ups).",
      },
      {
        question:
          "How long before I see results in the audit scores?",
        answer:
          "Citation pillar improvements appear within 2-4 weeks as you seed responses. AI Presence improvements take 4-8 weeks because AI models need to re-crawl the threads where you've placed citations. Entity and Review improvements depend on how quickly you update profiles and collect reviews. Press improvements correlate with campaign timing.",
      },
      {
        question:
          "Can I white-label the reports?",
        answer:
          "Yes. Reports use your agency logo, name, and branding colors. Your client sees the report as coming from your agency, with MentionLayer's platform powering the data behind the scenes.",
      },
    ],
    sections: [
      {
        id: "monthly-audit-comparison",
        title: "Monthly Audit Comparison",
        content: `The most powerful proof of ROI is the before/after audit comparison. Run audits monthly and the trend line tells the story.

[Screenshot: Month-over-month audit comparison showing score improvements across all 5 pillars]

**What the comparison shows:**
- **Composite score trajectory** — Your overall AI Visibility Score plotted over time
- **Pillar-by-pillar movement** — Which pillars improved, by how much, and which need more work
- **Delta highlights** — "+12 points in Citations" or "-3 in Reviews" with explanations for each change
- **Action plan progress** — Which recommended actions from previous audits have been completed and their measured impact

**The narrative arc for clients:**
Month 1: "Your AI Visibility Score is 28/100. Competitors dominate. Here's the plan."
Month 2: "Score is now 41/100 (+13). Citations doubled. AI models starting to notice."
Month 3: "Score is now 58/100 (+17). Perplexity now recommends you for 3 key terms."
Month 6: "Score is 74/100. You're the #2 recommended brand in your category."

This story is concrete, measurable, and impossible to argue with. No other SEO tool provides this level of AI visibility tracking.`,
      },
      {
        id: "competitor-intelligence",
        title: "Competitor Intelligence Reports",
        content: `MentionLayer tracks competitor data alongside yours, enabling side-by-side intelligence reports.

[Screenshot: Competitor comparison report showing side-by-side metrics across all 5 pillars]

**Competitor report includes:**
- **Share of model comparison** — Your brand vs competitors across all AI models
- **Citation footprint** — Number of forum mentions per competitor per platform
- **Review presence** — Review counts and ratings per competitor per platform
- **Press coverage** — Media mentions and authority scores
- **Entity completeness** — Platform presence comparison
- **Trend comparison** — Are you gaining ground or falling behind?

**Using competitor data strategically:**
- Identify which competitor is strongest on which platform
- Find platforms where no competitor has strong presence (blue ocean)
- Track when a competitor makes a significant move (sudden review spike, press campaign)
- Use competitor data in client pitches: "Your top competitor has 70% share of model. You have 8%."`,
      },
      {
        id: "client-reporting",
        title: "Client Reporting Best Practices",
        content: `MentionLayer generates professional client reports that demonstrate clear, measurable value.

[Screenshot: PDF report preview showing branded layout with charts, scores, and action items]

**Report structure:**
1. **Executive Summary** — One paragraph highlighting key wins and focus areas
2. **AI Visibility Score** — Current score with month-over-month trend
3. **Pillar Breakdown** — Each pillar with score, change, and key findings
4. **Work Completed** — Citations placed, reviews generated, press campaigns run
5. **AI Monitor Results** — Share of model trends with model-by-model breakdown
6. **Competitor Landscape** — Where you stand vs competitors
7. **Next Month's Plan** — Recommended actions for the coming period

**Reporting cadence:**
- **Weekly** — Quick status update (automated email: responses posted, new threads found)
- **Monthly** — Full audit comparison report (PDF deliverable)
- **Quarterly** — Deep-dive strategic review with competitor intelligence

**Tips for impactful client reports:**
- Lead with the composite score change: "+17 points this month"
- Include specific wins: "3 Reddit threads now cite your brand that didn't last month"
- Show competitor context: "You closed the gap with [competitor] by 15%"
- End with clear next steps: "Next month we're targeting YouTube gaps and G2 reviews"`,
      },
      {
        id: "ga4-attribution",
        title: "GA4 Attribution Tracking",
        content: `Connect Google Analytics 4 to track the traffic and conversions generated by your citation seeding campaigns.

[Screenshot: GA4 attribution dashboard showing traffic from citation sources with conversion tracking]

**What GA4 attribution tracks:**
- **Referral traffic** from Reddit, Quora, and other platforms where citations were placed
- **Conversion events** from citation-driven visitors (form fills, sign-ups, purchases)
- **Landing page performance** for pages linked in citation responses
- **User journey** — how citation-driven visitors navigate your site after arriving

**Setup:**
1. Connect your GA4 property in MentionLayer settings
2. MentionLayer automatically identifies referral traffic from platforms where you've placed citations
3. UTM parameters on links in your responses enable precise attribution
4. Conversion data appears in your monthly reports alongside AI visibility metrics

**Attribution insights:**
- Which platforms drive the most conversion-quality traffic
- Which keywords produce the highest-value citation placements
- Which response variants (casual, expert, story) drive the most clicks
- ROI calculation: credited conversions × average conversion value = campaign revenue attribution

This data closes the loop from "AI visibility" to "revenue impact" — the ultimate proof that citation seeding and AI optimization generate real business results.`,
      },
    ],
  },
];

export function getArticleBySlug(slug: string): HelpArticle | undefined {
  return helpArticles.find((a) => a.slug === slug);
}

export function getAllSlugs(): string[] {
  return helpArticles.map((a) => a.slug);
}
